@startuml
hide empty members
skinparam shadowing false

class HandEffect << (E, orange) >>

class PatternEffect << (E, orange) >>

class MoveEffect << (E, orange) >>

class PhaseEffect << (E, orange) >>

@enduml