@startuml
'https://plantuml.com/sequence-diagram

autonumber

'Press start game in MenuComponent - Pass the settings and fill the hand
View --> ViewSubscriber : GameBoardInitialization
Model --> ModelSubscriber: StartGameBoardMessage
InternalView -> InternalViewSubscriber: UpdateGamePhaseView(WindPhase)
View -> ViewSubscriber: UpdateGamePhaseModel(WindPhase)
Model --> ModelSubscriber: RefreshMessage

loop (winning condition satisfied)
    'WindPhase - only grid enabled - click on grid - switch to WaitingPhase
    View -> ViewSubscriber: ResolvePatternChoice
    Model --> ModelSubscriber: RefreshMessage
    InternalView -> InternalViewSubscriber: UpdateGamePhaseView(WaitingPhase)
    View -> ViewSubscriber: UpdateGamePhaseModel(WaitingPhase)
    Model --> ModelSubscriber: RefreshMessage

    'Toggle discard cards on deck - requires pressing a button - WaitingPhase ↔ RedrawCardsPhase
    alt (discard button pressed)
        InternalView -> InternalViewSubscriber: InitializeDiscardProcedureMessage
        'InternalView -> InternalViewSubscriber: UpdateGamePhaseView(RedrawCardsPhase)
        View -> ViewSubscriber: UpdateGamePhaseModel(RedrawCardsPhase)

        'RedrawCardsPhase - hand and deck enabled
        'Toggle highlight on standard card
        InternalView -> InternalViewSubscriber: ToggleCardInListMessage

        alt (discard button confirmation pressed)
            InternalView -> InternalViewSubscriber: ConfirmDiscardMessage
            View -> ViewSubscriber: DiscardCardMessage
            View -> ViewSubscriber: DrawCardMessage
            InternalView -> InternalViewSubscriber: UpdateGamePhaseView(ExtraActionPhase)
            View -> ViewSubscriber: UpdateGamePhaseModel(ExtraActionPhase)
        else (discard button cancellation pressed)
            InternalView -> InternalViewSubscriber: CancelDiscardMessage
            InternalView -> InternalViewSubscriber: UpdateGamePhaseView(WaitingPhase)
            View -> ViewSubscriber: UpdateGamePhaseModel(WaitingPhase)
        end
    else (card clicked)
        'WaitingPhase - hand and deck enabled
        'Toggle highlight on standard card - WaitingPhase ↔ PlayCardPhase
        InternalView -> InternalViewSubscriber: CandidateCardToPlayMessage
        alt (same card clicked)
            View -> ViewSubscriber: ResetPatternComputation
            'InternalView -> InternalViewSubscriber: UpdateGamePhaseView(WaitingPhase)
            View -> ViewSubscriber: UpdateGamePhaseModel(WaitingPhase)
            Model --> ModelSubscriber: RefreshMessage
        else (another card clicked)
            View -> ViewSubscriber: ResolvePatternComputation
            'InternalView -> InternalViewSubscriber: UpdateGamePhaseView(PlayCardPhase)
            View -> ViewSubscriber: UpdateGamePhaseModel(PlayCardPhase)
            Model --> ModelSubscriber: RefreshMessage
        end
    end

    'PlayCardPhase - grid (compass and dice) enabled - click - switch to ExtraActionPhase
    alt (grid clicked)
        View -> ViewSubscriber: ResolvePatternChoice
    else (dice or compass clicked)
        View -> ViewSubscriber: UpdateWindDirection
    end
    Model --> ModelSubscriber: RefreshMessage
    InternalView -> InternalViewSubscriber: UpdateGamePhaseView(ExtraActionPhase)
    View -> ViewSubscriber: UpdateGamePhaseModel(ExtraActionPhase)
    Model --> ModelSubscriber: RefreshMessage

    'Toggle highlight on special card - grid enabled - can only be done to play it, not to discard
    alt (same card clicked)
        View -> ViewSubscriber: ResetPatternComputation
    else (another card clicked)
        View -> ViewSubscriber: ResolvePatternComputation
    end
    View -> ViewSubscriber: ResolvePatternChoice

    'If no special card in hand or playable, skip ExtraActionPhase and switch to WindPhase automatically
    'ExtraActionPhase - end turn button and special cards enabled only - switch to WindPhase
    InternalView -> InternalViewSubscriber: UpdateGamePhaseView(WindPhase)
    View -> ViewSubscriber: UpdateGamePhaseModel(WindPhase)
end
@enduml