=== Processo di sviluppo

Il gruppo ha adottato una metodologia agile per lo sviluppo del progetto,
seguendo una forma di scrum meno stringente per adattarsi alle difficoltà e agli imprevisti,
senza compromettere l’organizzazione del lavoro.

Gli strumenti utilizzati per agevolare lo sviluppo includono:

* *IntelliJ*: per la revisione del codice e il pair programming tramite Code with me.
* *Discord*: per lo svolgimento delle riunioni da remoto.
* *GitHub*: sia come piattaforma per lo sviluppo e l'hosting del software tramite il VCS Git, che per le DevOps, la documentazione e gli strumenti di Project Management.
** *GitHub Pages*: il servizio è stato utilizzato per l'hosting del sito web statico della documentazione di progetto. In particolare sono stati utilizzati il linguaggio di markup https://asciidoc.org/[AsciiDoc] per la scrittura della relazione.
** *GitHub Projects* e *GitHub Issues*.

==== Divisione in sprint

Abbiamo deciso di dividere lo sviluppo dell'applicazione in sprint di circa due settimane ciascuno, ad
eccezione dell'ultimo

Ad ogni sprint era associata una riunione di inizio e una di fine per discutere del lavoro svolto e di quello futuro.
Abbiamo utilizzato come strumento il backlog di GitHub per tenere traccia dei task da svolgere e di quelli completati.

==== Pianificazione dei task negli sprint

Abbiamo utilizzato i concetti di Feature, User Story e Sprint Task per organizzare il lavoro.
Le Feature venivano utilizzate per delineare una implementazione di una grossa parte di lavoro (come poteva essere la View del gioco).
Le User Story venivano utilizzate per delineare una parte più piccola di lavoro, vista dal punto di vista dell'utente.
Gli Sprint Task erano task della stessa dimensione della User Story, ma visti dal punto di vista

Le issue permettono hanno permesso di tracciare e gestire in modo dettagliato task, bug e nuove funzionalità direttamente nei repository Git. Inoltre permettono di descrivere chiaramente le attività, di assegnare responsabili, assegnare tag e monitorare lo stato di avanzamento. La possibilità di collegare le issue ai commit facilita la tracciabilità delle modifiche e garantisce una maggiore trasparenza nel processo di sviluppo, fornendo accesso a un _issue log_ che riporta preziose informazioni storiche sull'andamento del progetto.

Dato che le issue da sole non permettono di implementare in modo ottimale la metodologia Scrum è stato impiegato https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects[GitHub Projects]. Questo servizio permette di pianificare gli sprint e di creare una _Scrum board_, tenendo traccia sia del product backlog che dello sprint backlog, oltre che dei compiti che si stanno svolgendo o che devono essere vagliati durante la sprint review o che sono stati completati.

L'adozione di una Scrum board ha permesso di impiegare un approccio visivo che ha facilitato la gestione delle attività, consentendo al team di stabilire a colpo d'occhio la priorità dei compiti e lo stato di avanzamento del progetto.

=== Template delle issue

Sono state definite delle linee guida per facilitare la creazione di issue rappresentanti i tipi di storie che costituiscono il backlog. In <<epic-issue-template>>, <<feature-issue-template>>, <<job-story-issue-template>>, <<user-story-issue-template>> e <<sprint-task-issue-template>>, sono riportate le indicazioni sul contenuto suggerito rispettivamente di epiche, feature, job story, user story e sprint task.

Si osserva che seguendo le linee guida è possibile tenere traccia delle relazioni che intercorrono tra le issue, potendo risalire rapidamente da uno sprint task fino all'epica a cui è connesso.

Inoltre per ciascuna storia sono definiti i criteri di accettazione, utilizzati durante la review di uno sprint, sia per stabilire quali storie possono essere considerate complete che lo stato di avanzamento del progetto rispetto alle milestone.

[#epic-issue-template]
.Contenuto del template per le issue relative a epiche.
[source]
----
# Description
Detailed description of the task and what needs to be done

# Acceptance Criteria
List acceptance criteria

# Additional Notes
Include any additional information, attachments, or references
----

[#feature-issue-template]
.Contenuto del template per le issue relative a feature.
[source]
----
# Description
Detailed description of the feature, including its purpose and functionality

# Acceptance Criteria
List acceptance criteria

# Linked Epics
List linked epics

# Additional Notes
Include any additional information, attachments, or references
----

[#job-story-issue-template]
.Contenuto del template per le issue relative a job story.
[source]
----
When [situation]
I want to [motivation]
so I can achieve [outcome]

# Situation
Optional detailed description of the situation or context in which the need arises.

# Motivation
Optional detailed description of the motivation or reason behind the need

# Expected Outcome
Optional detailed description of the desired outcome or benefit

# Linked Features
List linked features

# Acceptance Criteria
List acceptance criteria

# Additional Notes
Include any additional information, attachments, or references
----

[#user-story-issue-template]
.Contenuto del template per le issue relative a user story.
[source]
----
As a [user role]
who is in [situation]
I want to [desired feature]
so that [value/benefit]

# User Role
Optional detailed description of the user role.

# Situation
Optional detailed description of the situation or context in which the need arises.

# Desired Feature
Optional detailed description of the motivation or reason behind the need

# Value
Optional detailed description of the desired outcome or benefit

# Linked Features
List linked features

# Acceptance Criteria
List acceptance criteria

# Additional Notes
Include any additional information, attachments, or references
----

[#sprint-task-issue-template]
.Contenuto del template per le issue relative a sprint task.
[source]
----
# Description
Detailed description of the task and what needs to be done

# Acceptance Criteria
List acceptance criteria

# Linked Stories
List linked user and/or job stories

# Additional Notes
Include any additional information, attachments, or references
----

=== Gestione del backlog

Per la definizione delle storie si effettua la creazione di una issue in un repository dell'organizzazione, utilizzando uno dei quattro template mostrati in <<Template delle issue>>. Ciascuno di questi template associa a una issue un tag per identificarne il tipo. Si distingue tra _sprint task_, _user story_, _feature_ ed _epiche_.

Al momento della creazione della issue l'associazione al progetto avviene in modo automatico grazie ai workflow automatizzati di GitHub. In aggiunta è inizializzato il ciclo di vita della issue all'interno del progetto, impostando il suo status a _Backlog_, in modo da segnalare che la storia è pronta per essere resa lavorabile. Gli altri stati che può assumere una issue sono _Ready_, _In Progress_, _In Review_ e _Done_.

Lo stato in progress è impostato dai membri del team quando iniziano a lavorare su una storia o un task.

Lo stato in review è impostato dai membri del team quando completano una storia e ritengono che i criteri di accettazione siano soddisfatti. Al termine dello sprint, durante lo sprint review meeting, si mostrano e discutono i risultati con il product owner e gli altri stakeholder. Se il product owner fornisce l'approvazione, la storia è spostata nello stato done. In caso contrario o la storia è rifiutata ed è spostata nuovamente nello stato in progress, oppure è scartata ed eventualmente è sostituita con una o più nuove storie.

Nel caso si verifichi un bug risolvibile che blocca la lavorazione di una storia o che sia necessario apportare correzioni a una storia già completata, non si cambia lo stato della storia ma si crea un nuovo sprint task. Questo task avrà stato ready, una priorità adeguata al grado di urgenza e descriverà il problema e come effettuare la correzione.

Allo scopo di mantenere ogni sprint un processo di sviluppo a sè stante, abbiamo deciso di utilizzare un branch diverso per ogni sprint, per poi ripusharlo sul branch main una
volta terminato.

=== Sprints


==== Meeting
All'inizio dello sviluppo, abbiamo deciso di fissare delle riunioni settimanali per discutere del backlog. Allo scopo
di mantenerci però sempre aggiornati, abbiamo anche deciso di confrontarci giornalmente tramite Discord e Telegram.
In caso di necessità abbiamo fissato riunioni straordinarie.

==== Nomenclatura dei commit

L'adozione dei commit convenzionali ha permesso di definire in modo univoco e standardizzato come scrivere i messaggi di commit Git. In particolare nell'ambito di questo progetto sono stati utilizzati i seguenti tipi di commit:

- `feat`: commit che aggiunge o rimuove feature;
- `fix`: commit che corregge un bug;
- `docs`: commit che modifica la documentazione;
- `style`: commit che non modifica il significato del codice, relativo ad esempio a spazi bianchi, formattazione, etc;
- `refactor`: commit che ristruttura il codice ma non modifica il comportamento delle API;
- `test`: commit che aggiunge dei test mancanti o modifica quelli esistenti;
- `build`: commit relativi a strumenti di build automation o a pipeline di CI/CD;

- `chore`: commit che non modificano il codice che va in produzione.

==== Scelta degli strumenti di test/build/continuos integration

